import { Coffee } from "../components/coffee-data-table/columns";

export interface DdbData {
  lastEvaluatedKey: string;
  entities: Coffee[];
}

export const getDummyData = (): DdbData => {
  return { lastEvaluatedKey: "", entities: dummyData };
};

export const getLatestDummyShot = () => {
  return dummyData[dummyData.length - 1];
};

export const dummyData: Coffee[] = [
  {
    id: "1",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-14"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Tastes like blueberries",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "2",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-14"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Floral and fruity flavors",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "3",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-14"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Rich chocolatey taste",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "4",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-15"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Smooth and nutty flavor",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "5",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-15"),
    grindSetting: 9,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Bright and citrusy taste",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "6",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-16"),
    grindSetting: 9,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Caramel and toffee notes",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "7",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-16"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Balanced and smooth flavor",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "8",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-17"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Hints of brown sugar and cocoa",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "9",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-17"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Delicate and tea-like taste",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "10",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-18"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Toasted almond flavor",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "11",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-18"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Sweet and fruity aroma",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "12",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-18"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Smooth and chocolatey taste",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "13",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-19"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Rich and full-bodied flavor",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "14",
    userId: "static_user_id",
    beans: "Test Origin",
    extractionMethod: "Espresso",
    roaster: "Test Roaster",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-19"),
    grindSetting: 10,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Subtle floral undertones",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "15",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-20"),
    grindSetting: 10,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Smooth and balanced profile",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "16",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-20"),
    grindSetting: 10,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Notes of caramel and honey",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "17",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-20"),
    grindSetting: 10,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Bright and fruity acidity",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "18",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-21"),
    grindSetting: 10,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Earthy and spicy flavors",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "19",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-22"),
    grindSetting: 10,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Bold and robust taste",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "20",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-22"),
    grindSetting: 9,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Spicy and aromatic profile",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "21",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-23"),
    grindSetting: 9,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Floral and fruity flavors",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "22",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-23"),
    grindSetting: 9,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Rich chocolatey taste",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "23",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-24"),
    grindSetting: 9,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Smooth and nutty flavor",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "24",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-24"),
    grindSetting: 9,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Bright and citrusy taste",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "25",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-04"),
    shotDate: new Date("2024-04-25"),
    grindSetting: 9,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Caramel and toffee notes",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 3,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "26",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-16"),
    shotDate: new Date("2024-04-26"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Balanced and smooth flavor",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: -4,
    muddyWatery: 3,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "27",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-16"),
    shotDate: new Date("2024-04-26"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Hints of brown sugar and cocoa",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 5,
    muddyWatery: -2,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "28",
    userId: "static_user_id",
    beans: "Another Origin",
    extractionMethod: "Espresso",
    roaster: "Another Roaster",
    roastDate: new Date("2024-04-16"),
    shotDate: new Date("2024-04-26"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Delicate and tea-like taste",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: 0,
    muddyWatery: 0,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "29",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    roastDate: new Date("2024-04-16"),
    shotDate: new Date("2024-04-27"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Toasted almond flavor",
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    acidityBitterness: -3,
    muddyWatery: 5,
    updatedAt: new Date("2024-04-14"),
  },
  {
    id: "30",
    userId: "static_user_id",
    beans: "Papua New Guinea",
    extractionMethod: "Espresso",
    roaster: "Proud Mary",
    shotDate: new Date("2024-04-27"),
    grindSetting: 11,
    brewTimeSeconds: getRandomBrewTime(),
    weightInGrams: getRandomWeightIn(),
    weightOutGrams: getRandomWeightOut(),
    rating: getRandomRating(),
    notes: "Sweet and fruity aroma \n testing newlines \n and more",
    acidityBitterness: 1,
    espressoMachine: "Gaggia Classic Pro",
    grinder: "Mazzer Mini Electric B",
    muddyWatery: -3,
    updatedAt: new Date("2024-04-14"),
  },
];

function getRandomWeightIn(): number {
  /**
   * Returns a random weight in grams between 18 and 18.5.
   */
  return parseFloat((Math.random() * 0.5 + 18).toFixed(1));
}

function getRandomWeightOut(): number {
  /**
   * Returns a random weight out grams between 43 and 58.
   */
  return parseFloat((Math.random() * 5 + 43).toFixed(1));
}

function getRandomBrewTime(): number {
  /**
   * Returns a random brew time in seconds between 20 and 35.
   */
  return Math.floor(Math.random() * 15 + 20);
}

function getRandomRating(): number {
  return Math.round(Math.random() * 10)
}
