name: react
services:
  development:
    build:
      context: .
      target: development
    ports:
      - 5173:5173
    volumes:
      - ./src:/code/src:ro

  production:
    build:
      context: .
      target: builder
    ports:
      - 80:80
      - 443:443
